config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# resources :sushis
get '/sushis', to: "sushis#index", as: "sushis"
get '/sushis/new', to: "sushis#new", as: "new_sushi"
get '/sushis/:id', to: "sushis#show", as: "sushi"
get '/sushis/:id/edit', to: "sushis#edit", as: "edit_sushi"
post '/sushis', to: "sushis#create"
patch '/sushis/:id', to: "sushis#update"
delete '/sushis/:id', to: "sushis#destroy"
get '/', to: "sushis#home"
get '/:anything', to: "application#wrong_page"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sushi.rb
class Sushi < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def wrong_page
    render "/wrong_page"
  end
end

app/controllers/sushis_controller.rb
class SushisController < ApplicationController
  def index
    @sushis = Sushi.all
  end

  def show
    current_sushi
  end

  def new
    @sushi = Sushi.new
  end

  def create
    @sushi = Sushi.create(sushi_params)
    redirect_to sushi_path(@sushi)
  end

  def edit
    current_sushi
  end

  def update
    current_sushi
    @sushi.update(sushi_params)
    redirect_to sushi_path(@sushi)
  end

  def destroy
    current_sushi
    @sushi.destroy
    redirect_to sushis_path
  end

  def home; end

  private

  def sushi_params
    params.require(:sushi).permit(:name)
  end

  def current_sushi
    @sushi = Sushi.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Owl Cave Sushi</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <div class="background">
      <div class="container">
        <div class="row">
          <div class="col-xs-8">
            <h1> <a href="/">Owl Cave Sushi Cafe</a></h1>
            <h6> That sushi you like is back in style. </h6>
          </div>
          <div class="col-xs-4">
            <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/1181242-200.png" class="wrapping img-fluid img-responsive"/>
          </div>
        </div>
        <div class="row">
          <div class="well">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sushis/edit.erb
<h1>
  Mix it up!
</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <p>Alter this sushi to your heart's content:</p>
      <br/>
      <%= form_for @sushi do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br/>
      <br/>
      <%= f.submit %>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top img-responsive" src="https://images.bigcartel.com/product_images/198520063/BlueRose.jpg?auto=format&fit=max&h=1000&w=1000"/>
      <div class="card-block">
        <p class="card-text">Sushi so good you won't believe it exists in nature!</p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/sushis/index.erb
<h1>Browse our Mountains of Sushi:</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <% @sushis.map do |sushi| %>
        <li>
          <%= link_to sushi.name, sushi_path(sushi) %>
        </li>
      <% end %>
    </div>
    <div class="col-xs-6">
      <div class="background-div">
        <img class="img-responsive fixed-image img-circle" src="https://cdn.dribbble.com/users/644992/screenshots/1772842/twin_peaks.jpg"/>
      </div>
    </div>
  </div>
</div>

app/views/sushis/new.erb
<h1>Build-your-own sushi!</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <br/>
      <p>You name it, we make it. Fill out your preference and our waiter will bring it directly to you.</p>
      <br/>
      <%= form_for @sushi do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br/>
      <br/>
      <%= f.submit %>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top img-responsive" src="https://i.pinimg.com/736x/58/b1/d7/58b1d789616aa6ef4ae6b56cf86af16b--coffee-geek-drink-coffee.jpg"/>
      <div class="card-block">
        <p class="card-text">Every sushi order comes with a cup of damn fine coffee.</p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/sushis/show.erb
<h2>
  Every day, once a day, give yourself a present.
</h2>

<p>
  Your fresh sushi and hot coffee have arrived! Please check to make sure it is to your specifications.</p>
<div class="wrapping">
  <img class="img-responsive" src="http://sweetclipart.com/multisite/sweetclipart/files/sushi_rolls_futomaki_ebi.png"/>
</div>

<h4 class="red-text">
  Name:
  <%=@sushi.name%>
</h4>
<h6><%= link_to "Edit", edit_sushi_path(@sushi) %>
  |
  <%= link_to "Delete", @sushi, method: :delete, data: { confirm: "Really?" } %></h6>